trying to patch error

diff --git a/sci-biology/fsl/files/fsl-5.0.10-setup.patch b/sci-biology/fsl/files/fsl-5.0.10-setup.patch
--- a/sci-biology/fsl/files/fsl-5.0.10-setup.patch
+++ b/sci-biology/fsl/files/fsl-5.0.10-setup.patch
@@ -103,7 +103,19 @@ diff -Naur fsl.orig/extras/build fsl/extras/build
    PROJECTS="${PROJECTS} libiconv"
  fi
 -PROJECTS="${PROJECTS} libgd libgdc libprob libcprob newmat cprob newran fftw"
+-PROJECTS="${PROJECTS} boost libxml2-2.9.2 libxml++-2.34.0 libsqlite libnlopt ../include/armawrap/dummy_newmat"
 +PROJECTS="libgdc libprob libcprob newmat cprob newran"
- PROJECTS="${PROJECTS} boost libxml2-2.9.2 libxml++-2.34.0 libsqlite libnlopt ../include/armawrap/dummy_newmat"
++PROJECTS="${PROJECTS} boost libsqlite libnlopt ../include/armawrap/dummy_newmat"
  for projname in $PROJECTS; do
      if [ -d $FSLESRCDIR/$projname ] ; then
+diff -Naur fsl.orig/src/mist-clean/Makefile fsl/src/mist-clean/Makefile
+--- fsl.orig/src/mist-clean/Makefile	2006-03-27 10:48:16.000000000 +0200
++++ fsl/src/mist-clean/Makefile	2018-10-08 16:16:01.180310611 +0200
+@@ -52,6 +52,6 @@
+ 		cp -r python/* ${DESTDIR}/python/mist
+ 
+ clean:
+-			rm ${OBJS} mist/mist.o mist/mist
++			rm -f ${OBJS} mist/mist.o mist/mist || echo "CLEAN could not locate some files scheduled for deletion."
+ 
+ .PHONY:		all clean installdata
