Update lustre patches
Package-Manager: portage-2.2.0_alpha173
RepoMan-Options: --force

diff --git a/sys-cluster/lustre/files/0009-LU-3117-build-zfs-0.6.1-kmod-dkms-compatibility.patch b/sys-cluster/lustre/files/0009-LU-3117-build-zfs-0.6.1-kmod-dkms-compatibility.patch
--- a/sys-cluster/lustre/files/0009-LU-3117-build-zfs-0.6.1-kmod-dkms-compatibility.patch
+++ b/sys-cluster/lustre/files/0009-LU-3117-build-zfs-0.6.1-kmod-dkms-compatibility.patch
@@ -1,7 +1,7 @@
-From 1542e6ffacd11b54b5ffe71b0a107be0ce20732d Mon Sep 17 00:00:00 2001
+From eb4e257e6d9bab8401bc746a3d00c80be5748e92 Mon Sep 17 00:00:00 2001
 From: Brian Behlendorf <behlendorf1@llnl.gov>
 Date: Thu, 28 Mar 2013 12:18:27 -0700
-Subject: [PATCH 11/11] LU-3117 build: zfs-0.6.1 kmod+dkms compatibility
+Subject: [PATCH 9/9] LU-3117 build: zfs-0.6.1 kmod+dkms compatibility
 
 With the release of zfs-0.6.1 the default install location of
 the zfs kmod headers and objects has changed.  The kmod headers
@@ -50,14 +50,14 @@ Signed-off-by: Nathaniel Clark <nathaniel.l.clark@intel.com>
  autoMakefile.am                |   2 +-
  config/lustre-build-ldiskfs.m4 |   1 -
  config/lustre-build-zfs.m4     | 731 ++++++++++++++++++-----------------------
- contrib/lbuild/lbuild          |   2 +
+ contrib/lbuild/lbuild          |  72 +---
  lustre.spec.in                 |   2 +-
  lustre/osd-zfs/Makefile.in     |   3 +-
  lustre/utils/Makefile.am       |   6 +-
- 7 files changed, 326 insertions(+), 421 deletions(-)
+ 7 files changed, 340 insertions(+), 477 deletions(-)
 
 diff --git a/autoMakefile.am b/autoMakefile.am
-index 93608de..5880d1c 100644
+index bfec407..27e16c1 100644
 --- a/autoMakefile.am
 +++ b/autoMakefile.am
 @@ -1,4 +1,4 @@
@@ -847,9 +847,22 @@ index bfc647f..507afd8 100644
 +	AM_CONDITIONAL(ZFS_ENABLED, test x$enable_zfs = xyes)
  ])
 diff --git a/contrib/lbuild/lbuild b/contrib/lbuild/lbuild
-index f389505..3eda63f 100755
+index f389505..d22a9f6 100755
 --- a/contrib/lbuild/lbuild
 +++ b/contrib/lbuild/lbuild
+@@ -1009,10 +1009,10 @@ build_spl_zfs() {
+     local pkg
+     for pkg in spl zfs; do
+ 
+-        local rpmmod spldir
++        local dkmspkg
+ 
+         [ "$pkg" == "zfs" ] && spldir="$(ls -d $TOPDIR/usr/src/spl-*/*)"
+-        rpmmod=$pkg-modules
++        dkmspkg=$pkg-dkms
+ 
+         # need to fetch the repo in order to build it.
+         # default to github but allow override
 @@ -1020,6 +1020,8 @@ build_spl_zfs() {
  
          pushd $pkg || return 255
@@ -859,6 +872,85 @@ index f389505..3eda63f 100755
          # XXX - _having_ to give a package a kernel just to have it configure
          #       enough to do a "make dist" is truely bogus!
          if  ! ./configure --with-linux=${LINUX} \
+@@ -1028,66 +1030,24 @@ build_spl_zfs() {
+             popd
+             return 255
+         fi
+-        popd
+-
+-        # XXX - dirty hack time.  ~sigh~
+-        #       because the spl tarball contains two .spec files, we cannot
+-        #       simply rebuild the tarball
+-        ln $pkg/$pkg-*.tar.gz $TOPDIR/SOURCES ||
+-            error "failed to link $pkg/$pkg-*.tar.gz into $TOPDIR/SOURCES"
+ 
+-        # First build the userspace tools RPMs
+-        if ! $RPMBUILD $targets -bb $pkg/$pkg.spec \
+-            --nodeps -v \
+-            --define "configure_args ${CONFIGURE_FLAGS}" \
+-            --define "_tmppath /var/tmp" \
+-            --define "_topdir $TOPDIR" 2>&1; then
+-            return 255
+-        fi
++	make rpm || return 255
+ 
+-        if $DO_SRC; then
+-            if ! $RPMBUILD -bs $pkg/$pkg.spec \
+-                --nodeps -v \
+-                --define "configure_args ${CONFIGURE_FLAGS}" \
+-                --define "_tmppath /var/tmp" \
+-                --define "_topdir $TOPDIR" 2>&1; then
+-                return 255
+-            fi
+-        fi
++	if $DO_SRC; then
++	    make srpm || return 255
++	    mkdir -p $TOPDIR/SRPMS/
++	    mv $pkg*.src.rpm $TOPDIR/SRPMS/
++	fi
+ 
+-        # Now the kernel module RPMs
+-        # Need to provide pointers to the lustre kernel source, objects, usr/src
+-        if ! $RPMBUILD $targets -bb $pkg/$rpmmod.spec \
+-            --nodeps -v \
+-            --define "require_kdir ${linux}" \
+-            ${linuxobj:+--define "require_kobj ${linuxobj}"} \
+-            ${spldir:+--define "require_spldir ${spldir}"} \
+-            --define "configure_args ${CONFIGURE_FLAGS}" \
+-            --define "_usrsrc $TOPDIR/usr/src" \
+-            --define "kver $kver" \
+-            --define "_tmppath /var/tmp" \
+-            --define "_topdir $TOPDIR" 2>&1; then
+-            return 255
+-        fi
++	mkdir -p $TOPDIR/RPMS/$(basearch)/ $TOPDIR/RPMS/noarch/
++	mv $pkg*.noarch.rpm $TOPDIR/RPMS/noarch/
++	mv *$pkg*.$(basearch).rpm $TOPDIR/RPMS/$(basearch)/
+ 
+-        if $DO_SRC; then
+-            if ! $RPMBUILD -bs $pkg/$rpmmod.spec \
+-                --nodeps -v \
+-                --define "require_kdir ${linux}" \
+-                ${linuxobj:+--define "require_kobj ${linuxobj}"} \
+-                ${spldir:+--define "require_spldir ${spldir}"} \
+-                --define "configure_args ${CONFIGURE_FLAGS}" \
+-                --define "_usrsrc $TOPDIR/usr/src" \
+-                --define "kver $kver" \
+-                --define "_tmppath /var/tmp" \
+-                --define "_topdir $TOPDIR" 2>&1; then
+-                return 255
+-            fi
+-        fi
++        popd
+ 
+-        # We have built the rpms for the package. No we need to extract the
++        # We have built the rpms for the package. Now we need to extract the
+         # contained files so we can build further things against them
+-        local rpm=$(ls $TOPDIR/RPMS/*/$rpmmod-devel-*.rpm)
++        local rpm=$(ls $TOPDIR/RPMS/noarch/$dkmspkg-*.noarch.rpm)
+ 
+         # cpio only extract to pwd so we need to go there.
+         pushd $TOPDIR
 diff --git a/lustre.spec.in b/lustre.spec.in
 index edd02f5..11ff302 100644
 --- a/lustre.spec.in
